#!/usr/bin/env zsh
# Adapted from https://github.com/romkatv/dotfiles-public/blob/master/.purepower.
# If you copy this file, keep the link to the original and this sentence intact; you are encouraged
# to change everything else.

if test -z "${ZSH_VERSION}"; then
	echo "purepower: unsupported shell; try zsh instead" >&2
	return 1
	exit 1
fi

function p10kprompt() {
	emulate -L zsh && setopt no_unset pipe_fail

	typeset -ga POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
	status
	dir  # current directory
	vcs  # git status
	kubecontext

	)

	typeset -ga POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
	custom_rprompt          # the output of function `custom_rprompt()` if it is defined
		# context                 # user@host
		# time                  # current time
		)

		local ins='$'
		local cmd=':'
		if (( ${PURE_POWER_USE_P10K_EXTENSIONS:-1} )); then
			local p="\${\${\${KEYMAP:-0}:#vicmd}:+${${ins//\\/\\\\}//\}/\\\}}}"
			p+="\${\${\$((!\${#\${KEYMAP:-0}:#vicmd})):#0}:+${${cmd//\\/\\\\}//\}/\\\}}}"
		else
			local p=$ins
		fi

		typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
		typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
		typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
		typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
		typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{%(?.2.1)}$p%f "

		typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
		typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
		typeset -g POWERLEVEL9K_WHITESPACE_BETWEEN_{LEFT,RIGHT}_SEGMENTS=

		typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
		typeset -g POWERLEVEL9K_DIR_{ETC,HOME,HOME_SUBFOLDER,DEFAULT,NOT_WRITABLE}_BACKGROUND=none
		typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=3
		typeset -g POWERLEVEL9K_DIR_{HOME,HOME_SUBFOLDER,ETC,DEFAULT}_FOREGROUND=4
		typeset -g POWERLEVEL9K_{ETC,FOLDER,HOME,HOME_SUB,LOCK}_ICON=
		typeset -g POWERLEVEL9K_DIR_HYPERLINK=false

		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED,LOADING}_BACKGROUND=none
		typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
		typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=6
		typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3
		typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=5
		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND
		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_INCOMING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_OUTGOING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASHFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
		typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND=1
		typeset -g POWERLEVEL9K_VCS_LOADING_ACTIONFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_LOADING_FOREGROUND
		typeset -g POWERLEVEL9K_VCS_{GIT,GIT_GITHUB,GIT_BITBUCKET,GIT_GITLAB,BRANCH}_ICON=
		typeset -g POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$'%{\b|%}'
		typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
		typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
		typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'
		typeset -g POWERLEVEL9K_VCS_STASH_ICON='*'
		typeset -g POWERLEVEL9K_VCS_TAG_ICON=$'%{\b#%}'

		typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED}_MAX_NUM=99
		typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
		typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
		typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'

		typeset -g POWERLEVEL9K_STATUS_OK=false
		typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none
		typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
		typeset -g POWERLEVEL9K_CARRIAGE_RETURN_ICON=

		typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
		typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=none
		typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=5
		typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=none
		typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_COLOR=2
		typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON='%'

		typeset -g POWERLEVEL9K_CUSTOM_RPROMPT=custom_rprompt
		typeset -g POWERLEVEL9K_CUSTOM_RPROMPT_BACKGROUND=none
		typeset -g POWERLEVEL9K_CUSTOM_RPROMPT_FOREGROUND=4

		typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,ROOT,REMOTE_SUDO,REMOTE,SUDO}_BACKGROUND=none
		typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,REMOTE_SUDO,REMOTE,SUDO}_FOREGROUND=7
		typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=3

		typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=none
		typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=6
		typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
		typeset -g POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER=
		typeset -g POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=

		typeset -g POWERLEVEL9K_ANACONDA_BACKGROUND=none
		typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=6
		typeset -g POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=true
		typeset -g POWERLEVEL9K_ANACONDA_LEFT_DELIMITER=
		typeset -g POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=

		typeset -g POWERLEVEL9K_PYENV_BACKGROUND=none
		typeset -g POWERLEVEL9K_PYENV_FOREGROUND=6
		typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false

		typeset -g POWERLEVEL9K_PYTHON_ICON=

		typeset -g POWERLEVEL9K_TIME_BACKGROUND=none
		typeset -g POWERLEVEL9K_TIME_FOREGROUND=7
		typeset -g POWERLEVEL9K_TIME_ICON=

		typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

		typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=none
		typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=white
	}

p10kprompt

SCRIPT_PATH="${0:A:h}"
[[ -f "${SCRIPT_PATH}/powerlevel10k/powerlevel10k.zsh-theme" ]] && source ${SCRIPT_PATH}/powerlevel10k/powerlevel10k.zsh-theme
