directory:      ~/Desktop/music
library:        ~/.config/beets/library.blb
plugins:        scrub zero chroma discogs fromfilename
original_date:  yes
threaded:       yes
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Singletons/$artist/$title
    comp: Compilations/$album%aunique{}/$track - $artist - $title
import:
    move:     yes
zero:
    fields:     month day comments

